version: 2
jobs:
  build:
    working_directory: /go/src/github.com/aws/aws-sdk-go
    docker:
        - image: circleci/golang:1.13.3
    environment:
      GO111MODULE: "off"
      # When running in Docker in Circle, Go thinks there are 36 CPUs
      # which means the default number of parallel build processes will be 36
      # but using 36 build processes can lead to OOM errors
      # because according to https://circleci.com/docs/2.0/configuration-reference/#resource_class ,
      # the default Docker container only has 2 CPUs available.
      # We explicitly specify -p=4 to reduce the number of parallel build processes
      GOFLAGS: "-p=4"
    steps:
      - checkout
      - run: make get-deps
      - run: make ci-test

